sudo: required
services:
  - docker

before_install:
  - docker build -t oshianor/react-test -f ./client/Dockerfile.dev ./client/Dockerfile.dev


script:
  - docker run oshianor/react-test npm test -- --coverage
  
after_success:
  - docker build -t oshianor/multi-client ./client
  - docker build -t oshianor/multi-server ./server
  - docker build -t oshianor/multi-worker ./worker
  - docker build -t oshianor/multi-nginx ./nginx

  #login to docker hub cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #push images to docker hub
  - docker push oshianor/multi-client
  - docker push oshianor/multi-server
  - docker push oshianor/multi-worker
  - docker push oshianor/multi-nginx